"""Add mac_auto_release_list to config

Revision ID: 1730222a164f
Revises: 476dcd38f375
Create Date: 2025-10-05 21:57:57.955664

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1730222a164f'
down_revision = '476dcd38f375'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('application_config', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mac_auto_release_list', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('application_config', schema=None) as batch_op:
        batch_op.drop_column('mac_auto_release_list')

    # ### end Alembic commands ###
