"""Initial squashed migration

Revision ID: 1895553a2bfe
Revises: 
Create Date: 2025-10-13 19:02:44.965404

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1895553a2bfe'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('application_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scan_subnet', sa.String(length=18), nullable=True),
    sa.Column('dhcp_server_ip', sa.String(length=15), nullable=True),
    sa.Column('network_interface', sa.String(length=50), nullable=True),
    sa.Column('auto_release_threshold_hours', sa.Integer(), nullable=True),
    sa.Column('mac_auto_release_list', sa.Text(), nullable=True),
    sa.Column('dry_run_enabled', sa.Boolean(), nullable=False),
    sa.Column('discovery_method', sa.String(length=50), server_default='nmap', nullable=False),
    sa.Column('release_policy', sa.String(length=50), server_default='force', nullable=False),
    sa.Column('scan_interval_seconds', sa.Integer(), server_default='60', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('device',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ip_address', sa.String(length=15), nullable=False),
    sa.Column('mac_address', sa.String(length=17), nullable=False),
    sa.Column('vendor', sa.String(length=255), nullable=True),
    sa.Column('first_seen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('is_excluded', sa.Boolean(), nullable=False),
    sa.Column('lease_start_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('lease_duration_seconds', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('device', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_device_mac_address'), ['mac_address'], unique=True)

    op.create_table('historical_stat',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('releases_manual', sa.Integer(), nullable=False),
    sa.Column('releases_inactivity', sa.Integer(), nullable=False),
    sa.Column('releases_mac_list', sa.Integer(), nullable=False),
    sa.Column('total_devices_snapshot', sa.Integer(), nullable=False),
    sa.Column('active_devices_peak', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('date')
    )
    op.create_table('log_entry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('level', sa.String(length=10), nullable=True),
    sa.Column('message', sa.String(length=500), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))

    op.drop_table('user')
    op.drop_table('log_entry')
    op.drop_table('historical_stat')
    with op.batch_alter_table('device', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_device_mac_address'))

    op.drop_table('device')
    op.drop_table('application_config')
    # ### end Alembic commands ###
