"""Initial migration with Device, Config, and Log models.

Revision ID: 476dcd38f375
Revises: 
Create Date: 2025-10-05 20:00:21.071922

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '476dcd38f375'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('application_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scan_subnet', sa.String(length=18), nullable=True),
    sa.Column('dhcp_server_ip', sa.String(length=15), nullable=True),
    sa.Column('network_interface', sa.String(length=50), nullable=True),
    sa.Column('auto_release_threshold_hours', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('device',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ip_address', sa.String(length=15), nullable=False),
    sa.Column('mac_address', sa.String(length=17), nullable=False),
    sa.Column('vendor', sa.String(length=255), nullable=True),
    sa.Column('first_seen', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('last_seen', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('is_excluded', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('device', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_device_mac_address'), ['mac_address'], unique=True)

    op.create_table('log_entry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('level', sa.String(length=10), nullable=True),
    sa.Column('message', sa.String(length=500), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('log_entry')
    with op.batch_alter_table('device', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_device_mac_address'))

    op.drop_table('device')
    op.drop_table('application_config')
    # ### end Alembic commands ###
