"""Add last_seen_by to Device model

Revision ID: 5560f32b3714
Revises: 1895553a2bfe
Create Date: 2025-10-13 20:09:32.029109

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5560f32b3714'
down_revision = '1895553a2bfe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('device', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_seen_by', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('device', schema=None) as batch_op:
        batch_op.drop_column('last_seen_by')

    # ### end Alembic commands ###
