"""Add dry_run_enabled to ApplicationConfig

Revision ID: 5816a570ffa8
Revises: 05b2a0c1044f
Create Date: 2025-10-06 20:22:35.112197

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5816a570ffa8'
down_revision = '05b2a0c1044f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('application_config', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dry_run_enabled', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('application_config', schema=None) as batch_op:
        batch_op.drop_column('dry_run_enabled')

    # ### end Alembic commands ###
