"""Add HistoricalStat model

Revision ID: e4a7b2a5c1d9
Revises: 5816a570ffa8
Create Date: 2025-10-07 10:30:15.123456

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4a7b2a5c1d9'
down_revision = '5816a570ffa8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('historical_stat',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('releases_manual', sa.Integer(), nullable=False),
    sa.Column('releases_inactivity', sa.Integer(), nullable=False),
    sa.Column('releases_mac_list', sa.Integer(), nullable=False),
    sa.Column('total_devices_snapshot', sa.Integer(), nullable=False),
    sa.Column('active_devices_peak', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('date')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('historical_stat')
    # ### end Alembic commands ###
